/**
 * PK-4.0 API
 * API for the PK-4.0
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface Field {


    id?: string;

    name?: string;

    fieldType?: string;

    label?: string;

    required?: boolean;

    multipleSelect?: boolean;

    value?: string | string[];

    contentType?: string;

    placeholder?: string;

    options?: { label: string, value: string }[];

    enumOptionsTableId?: string;

    fieldHasStyle?: Array<models.FieldHasStyle>;

    fieldHasValidation?: Array<models.FieldHasValidation>;

    formHasField?: Array<models.FormHasField>;

    enumOptionsTable?: models.EnumOptionsTable;

    fieldTypeNavigation?: models.FieldType;

    /** Cutsom */
    disabled?: boolean;
    validations?: string[];
    styles?: string[];
    optionTable?: string;
    hidden?: boolean;

}
