/**
 * API Schnittstelle für die Prüfungskommision der Hochschule Augsburg
 * Hier sind alle Routen aufgelistet die zur verfügung stehen. Zuvor muss jedoch ein JWT Token überden Authorize Button hinzugefügt werden
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';
import { Selectable } from 'app/models';

export class FieldCreateDto {

    id?: string;

    name: string;

    fieldType: string;

    label?: string;

    required?: boolean;

    multipleSelect?: boolean;

    contentType?: string;

    placeholder?: string;

    optionsJson?: string;

    enumOptionsTableId?: string;

    styleIds?: Array<string>;

    validationIds?: Array<string>;

    // Custom

    value?: string | string[];

    options?: Array<Selectable>;

    // optionTable?: string; -> enumOptionsTableId

    constructor(obj: models.FieldDto = new models.FieldDto()) {
        this.id = obj.id;
        this.name = obj.name;
        this.fieldType = obj.fieldType;
        this.label = obj.label;
        this.required = obj.required;
        this.multipleSelect = obj.multipleSelect;
        this.contentType = obj.contentType;
        this.placeholder = obj.placeholder;
        this.enumOptionsTableId = obj.enumOptionsTableId;
        this.styleIds = obj.styleIds || [];
        this.validationIds = obj.validationIds || [];
        this.value = obj.value;

        this.options = (!obj.options && obj.optionsJson) ? JSON.parse(obj.optionsJson) : obj.options;
        this.optionsJson = obj.options ? JSON.stringify(obj.options) : obj.optionsJson;
    }
}
