/**
 * PK API
 * Move your app forward with the PK API
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface FormElement {


    /**
     * Unique identifier of the FormElement
     */
    id?: number;

    /**
     * Creation timestamp of the FormElement
     */
    created?: number;

    /**
     * Last timestamp of modification of the FormElement
     */
    modified?: number;

    /**
     * The Position of the FormElement in the Application itself
     */
    index?: number;

    /**
     * The Type of the Form Element (eg input, checkbox, radio, select, textarea)
     */
    elementType?: string;

    /**
     * Inique readable ID/Name
     */
    name?: string;

    /**
     * Input only - type of the input field (eg email, password, text)
     */
    type?: string;

    /**
     * The label of the FormElement
     */
    label?: string;

    /**
     * Flag to indicate if the FormElement is required or not
     */
    required?: boolean;

    /**
     * Placeholder for the input / textarea
     */
    placeholder?: string;

    /**
     * An Array of Strings for input validation
     */
    validations?: Array<string>;

    /**
     * Select only - ability to select multiple elements
     */
    multiple?: boolean;

    /**
     * The value or the values of the ApplicationAttribute (string or array)
     */
    value?: any;

    /**
     * Placeholder for the Form Control of Angular 2
     */
    formControl?: any;

    /**
     * Options for Radio and Select
     */
    options?: Array<models.FormOptions>;

    /**
     * Styles parameters for the visual appearance of the Application
     */
    styles?: Array<string>;
}
