/**
 * API Schnittstelle für die Prüfungskommision der Hochschule Augsburg
 * Hier sind alle Routen aufgelistet die zur verfügung stehen. Zuvor muss jedoch ein JWT Token überden Authorize Button hinzugefügt werden
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export class StatusDto {

    id: string;

    name: string;

    constructor(obj?: StatusDto) {
        obj = obj || ({} as any);
        this.id = obj.id;
        this.name = obj.name;
    }
}

export enum Status {
    CREATED = <any>'1',
    SUBMITTED = <any>'2',
    RESCINDED = <any>'3',
    PENDING = <any>'4',
    DEACTIVATED = <any>'5',
    ACCEPTED = <any>'6',
    DENIED = <any>'7',
}

export enum StatusName {
    CREATED = <any>'created',
    SUBMITTED = <any>'submitted',
    RESCINDED = <any>'rescinded',
    PENDING = <any>'pending',
    DEACTIVATED = <any>'deactivated',
    ACCEPTED = <any>'accepted',
    DENIED = <any>'denied',
}
