/**
 * PK-4.0 API
 * API for the PK-4.0
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import * as models from '../model/models';
import 'rxjs/Rx';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class ConferenceApi {
    protected basePath = 'https://pk.multimedia.hs-augsburg.de:8000/';
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * Add a Application to the Conference
     *
     * @param conferenceId ID of the Conference
     * @param applicationId The Application ID
     * @param token Accesstoken to authenticate with the API
     */
    public addApplicationToConference (conferenceId: string, applicationId: string, token?: number, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/conferences/{conferenceId}/applications/{applicationId}'
            .replace('{' + 'conferenceId' + '}', String(conferenceId))
            .replace('{' + 'applicationId' + '}', String(applicationId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'conferenceId' is not null or undefined
        if (conferenceId === null || conferenceId === undefined) {
            throw new Error('Required parameter conferenceId was null or undefined when calling addApplicationToConference.');
        }
        // verify required parameter 'applicationId' is not null or undefined
        if (applicationId === null || applicationId === undefined) {
            throw new Error('Required parameter applicationId was null or undefined when calling addApplicationToConference.');
        }
            headerParams.set('token', String(token));

        let requestOptions: RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Create new Conference
     *
     * @param token Accesstoken to authenticate with the API
     * @param conference new Conference Object
     */
    public addConference (token?: number, conference?: models.ConferenceCreateDto, extraHttpRequestParams?: any ) : Observable<models.ConferenceCreateDto> {
        const path = this.basePath + '/conferences';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
            headerParams.set('token', String(token));

        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(conference);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Delete Application of Conference
     *
     * @param conferenceId ID of the Conference
     * @param applicationId The Application ID
     * @param token Accesstoken to authenticate with the API
     */
    public deleteApplicationOfConference (conferenceId: string, applicationId: string, token?: number, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/conferences/{conferenceId}/applications/{applicationId}'
            .replace('{' + 'conferenceId' + '}', String(conferenceId))
            .replace('{' + 'applicationId' + '}', String(applicationId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'conferenceId' is not null or undefined
        if (conferenceId === null || conferenceId === undefined) {
            throw new Error('Required parameter conferenceId was null or undefined when calling deleteApplicationOfConference.');
        }
        // verify required parameter 'applicationId' is not null or undefined
        if (applicationId === null || applicationId === undefined) {
            throw new Error('Required parameter applicationId was null or undefined when calling deleteApplicationOfConference.');
        }
            headerParams.set('token', String(token));

        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Delete Conference with Id
     *
     * @param conferenceId ID of the Conference
     * @param token Accesstoken to authenticate with the API
     */
    public deleteConferenceById (conferenceId: string, token?: number, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/conferences/{conferenceId}'
            .replace('{' + 'conferenceId' + '}', String(conferenceId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'conferenceId' is not null or undefined
        if (conferenceId === null || conferenceId === undefined) {
            throw new Error('Required parameter conferenceId was null or undefined when calling deleteConferenceById.');
        }
            headerParams.set('token', String(token));

        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * GET Applications of Conference with Id
     *
     * @param conferenceId ID of the Conference
     * @param token Accesstoken to authenticate with the API
     */
    public getApplicationsByConference (conferenceId: string, token?: number, extraHttpRequestParams?: any ) : Observable<Array<models.ApplicationDto>> {
        const path = this.basePath + '/conferences/{conferenceId}/applications'
            .replace('{' + 'conferenceId' + '}', String(conferenceId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'conferenceId' is not null or undefined
        if (conferenceId === null || conferenceId === undefined) {
            throw new Error('Required parameter conferenceId was null or undefined when calling getApplicationsByConference.');
        }
            headerParams.set('token', String(token));

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * GET one Conference by Id
     *
     * @param conferenceId ID of the Conference
     * @param token Accesstoken to authenticate with the API
     */
    public getConferenceById (conferenceId: string, token?: number, extraHttpRequestParams?: any ) : Observable<models.ConferenceDtoApplicationDto> {
        const path = this.basePath + '/conferences/{conferenceId}'
            .replace('{' + 'conferenceId' + '}', String(conferenceId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'conferenceId' is not null or undefined
        if (conferenceId === null || conferenceId === undefined) {
            throw new Error('Required parameter conferenceId was null or undefined when calling getConferenceById.');
        }
            headerParams.set('token', String(token));

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    console.log(response.json());
                    return response.json();
                }
            });
    }

    /**
     * GET all Conferences
     * The Conferences Endpoint returns all Conferences
     * @param token Accesstoken to authenticate with the API
     * @param filter Filter the Result
     * @param sort Sort the Result
     */
    public getConferences (token?: number, filter?: string, sort?: string, extraHttpRequestParams?: any ) : Observable<Array<models.ConferenceDtoGuid>> {
        const path = this.basePath + '/conferences';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        if (filter !== undefined) {
            queryParameters.set('filter', String(filter));
        }

        if (sort !== undefined) {
            queryParameters.set('sort', String(sort));
        }

            headerParams.set('token', String(token));

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Update Conference with Id
     *
     * @param conferenceId ID of the Conference
     * @param token Accesstoken to authenticate with the API
     * @param conference Conference to Update
     */
    public updateConferenceById (conferenceId: string, token?: number, conference?: models.ConferenceCreateDto, extraHttpRequestParams?: any ) : Observable<models.ConferenceDtoApplicationDto> {
        const path = this.basePath + '/conferences/{conferenceId}'
            .replace('{' + 'conferenceId' + '}', String(conferenceId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'conferenceId' is not null or undefined
        if (conferenceId === null || conferenceId === undefined) {
            throw new Error('Required parameter conferenceId was null or undefined when calling updateConferenceById.');
        }
            headerParams.set('token', String(token));

        let requestOptions: RequestOptionsArgs = {
            method: 'PUT',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(conference);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

}
