/**
 * API Schnittstelle für die Prüfungskommision der Hochschule Augsburg
 * Hier sind alle Routen aufgelistet die zur verfügung stehen. Zuvor muss jedoch ein JWT Token überden Authorize Button hinzugefügt werden
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Http, Headers, RequestOptionsArgs, Response, URLSearchParams} from '@angular/http';
import {Injectable, Optional} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import * as models from '../model/models';
import 'rxjs/Rx';
import { Parse } from './../../shared/decorators/parse.decorator';

/* tslint:disable:no-unused-variable member-ordering */

'use strict';

@Injectable()
export class UserApi {
    protected basePath = 'https://pk.multimedia.hs-augsburg.de:8000/';
    public defaultHeaders : Headers = new Headers();

    constructor(protected http: Http, @Optional() basePath: string) {
        if (basePath) {
            this.basePath = basePath;
        }
    }

    /**
     * Add Role to User
     *
     * @param userId ID of the User
     * @param roleDto
     */
    @Parse('UserDetailDto')
    public addRoleToUser (userId: string, roleDto?: models.RoleDto, extraHttpRequestParams?: any ) : Observable<models.UserDetailDto> {
        const path = this.basePath + '/user/{userId}/role'
            .replace('{' + 'userId' + '}', String(userId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'userId' is not null or undefined
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling addRoleToUser.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(roleDto);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Create new AppUser from LDAP
     *
     * @param rzName The users rz name base 64 encoded
     * @param rzPassword The users rz password base 64 encoded
     * @param user The AppUser credentials
     */
    @Parse('UserDetailDto')
    public addUser (rzName?: string, rzPassword?: string, user?: models.UserCreateDto, extraHttpRequestParams?: any ) : Observable<models.UserDetailDto> {
        const path = this.basePath + '/users';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
            headerParams.set('rzName', String(rzName));

            headerParams.set('rzPassword', String(rzPassword));

        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        requestOptions.body = JSON.stringify(user);

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * GET one AppUser by Id
     *
     * @param userId ID of AppUser
     */
    @Parse('UserDetailDto')
    public getUserById (userId: string, extraHttpRequestParams?: any ) : Observable<models.UserDetailDto> {
        const path = this.basePath + '/users/{userId}'
            .replace('{' + 'userId' + '}', String(userId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'userId' is not null or undefined
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling getUserById.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * GET all AppUser
     * The Users Endpoint returns all Users
     */
    @Parse('UserListDto')
    public getUsers (extraHttpRequestParams?: any ) : Observable<Array<models.UserListDto>> {
        const path = this.basePath + '/users';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * Remove Role from User
     *
     * @param userId ID of the Application
     * @param roleId ID of the Role
     */
    public removeRoleFromUser (userId: string, roleId: string, extraHttpRequestParams?: any ) : Observable<{}> {
        const path = this.basePath + '/user/{userId}/role/{roleId}'
            .replace('{' + 'userId' + '}', String(userId))
            .replace('{' + 'roleId' + '}', String(roleId));

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        // verify required parameter 'userId' is not null or undefined
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling removeRoleFromUser.');
        }
        // verify required parameter 'roleId' is not null or undefined
        if (roleId === null || roleId === undefined) {
            throw new Error('Required parameter roleId was null or undefined when calling removeRoleFromUser.');
        }
        let requestOptions: RequestOptionsArgs = {
            method: 'DELETE',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    public login(username: string, password: string): Observable<any> {
        const path = this.basePath + '/connect/token';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;
        let requestOptions: RequestOptionsArgs = {
            method: 'POST',
            headers: headerParams,
            search: queryParameters
        };
        let urlSearchParams = new URLSearchParams();
        urlSearchParams.append('client_id', 'a2pkfrontend');
        urlSearchParams.append('client_secret', 'frontendsecret');
        urlSearchParams.append('grant_type', 'password');
        urlSearchParams.append('scope', 'api openid profile');
        urlSearchParams.append('username', 'patrick.schroeter@hs-augsburg.de');
        urlSearchParams.append('password', 'safePassword');
        requestOptions.body = urlSearchParams.toString();

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    const result = response.json();
                    return result;
                }
            });
    }

    @Parse('UserDetailDto')
    public getCurrentUser(): Observable<models.UserDetailDto> {
        const path = this.basePath + '/connect/userinfo';

        let queryParameters = new URLSearchParams();
        let headerParams = this.defaultHeaders;

        let requestOptions: RequestOptionsArgs = {
            method: 'GET',
            headers: headerParams,
            search: queryParameters
        };

        return this.http.request(path, requestOptions)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    public logout(): Observable<any> {
        return null;
    }

    @Parse('UserDetailDto')
    public updateUserById (userId: String, user?: models.UserDetailDto, extraHttpRequestParams?: any ) : Observable<models.UserDetailDto> {
        return new Observable(observer => {
            observer.next(user);
            observer.complete();
        });
    }

}
